-- Role: gumc
-- DROP ROLE IF EXISTS gumc;

CREATE ROLE gumc WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:+R6UP7jlF8Q8X4x4huBtNg==$k6V5tHEX/6/tZNgRxFQwgdxJHiHKxPjxgB0ulTfATy8=:C7WWQL23B4jBBB2obbL+bTBTxuKS4Hl5aOuoR29Ijnk=';

-- Role: lims
-- DROP ROLE IF EXISTS lims;

CREATE ROLE lims WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:wj+Mr9qfvFUswr6+cRovnw==$QYO8H5jtdpt6RWs/cYAjoFb6dYaIzS27GVZM45VtXKw=:dEp/Ryoy1M7lh/i5/ELpbSjLT/wCaRjTXOkxjf0SO6w=';

-- Role: mes_usr
-- DROP ROLE IF EXISTS mes_usr;

CREATE ROLE mes_usr WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:tpSqsb25OlqlZQg4r7NtQA==$+x+51GBE16HnmuJN4ScZGlPXzdsrPMGtzx07hTwPeMI=:CpeP5z+XaYo0LJ3vIMACpnehNYzRjsyimnFht1pdMZU=';


-- Role: wims
-- DROP ROLE IF EXISTS wims;

CREATE ROLE wims WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:adHH0HojOEl0Fe+7ZVlz1Q==$ybBo/zVIajuLl4m9FQ+yxd8/bjazsajGa2cA3vaPY8I=:QUMvhgf/0F4487YNLgodDuc30cH0Xrjg/XGjOYI35qw=';